services:
 nyc-postgres:
    image: postgres:16
    container_name: nyc-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: nyc_user
      POSTGRES_PASSWORD: nyc_password
      POSTGRES_DB: nyc_taxi
    ports:
      - "5432:5432"
    
    volumes:
      - nyc_postgres_data:/var/lib/postgresql/data
 minio:
    image: cgr.dev/chainguard/minio:latest
    container_name: minio
    restart: unless-stopped

    environment:
       MINIO_ROOT_USER: admin
       MINIO_ROOT_PASSWORD: minioadmin
    
    command: server /data --console-address ":9001"

    ports:
      - "9000:9000"
      - "9001:9001"
    
    volumes:
      - minio_data:/data
 metabase:
   image: metabase/metabase
   container_name: metabase
   restart: unless-stopped

   ports:
    - "3000:3000"
  
   volumes:
     - metabase_data:/metabase.db
volumes:
  nyc_postgres_data:
  minio_data:
  metabase_data:
